---
- name: python3 packages install by apt
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - python3-setuptools
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - python3-pip